import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1F2128',
  },
  header: {
    backgroundColor: '#1F2128',
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  subjectIcon: {
    width: 40,
    height: 40,
    backgroundColor: '#2A2D3A',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  subjectText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  headerRight: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#2A2D3A',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 3,
  },
  statText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 2,
  },
  emptyIconContainer: {
    width: 100,
    height: 100,
    backgroundColor: '#2A2D3A',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  scrollView: {
    flex: 1,
  },
  mapContainer: {
    paddingBottom: 120,
    minHeight: '100%',
  },
  backgroundContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    minHeight: height * 2,
    overflow: 'hidden',
  },
  spaceGradient: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: '#0F172A',
  },
  sunContainer: {
    position: 'absolute',
    top: -60,
    right: -60,
    width: 140,
    height: 140,
  },
  sun: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#FCD34D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sunGlow: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(252, 211, 77, 0.3)',
    top: -10,
    left: -10,
  },
  earthContainer: {
    position: 'absolute',
    top: '25%',
    left: '-10%',
    width: 160,
    height: 160,
  },
  earth: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: '#06B6D4',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  earthDetail: {
    width: '100%',
    height: '100%',
    borderRadius: 80,
    backgroundColor: 'rgba(34, 197, 94, 0.4)',
  },
  starsContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  star: {
    position: 'absolute',
    width: 3,
    height: 3,
    backgroundColor: '#FFFFFF',
    borderRadius: 2,
    shadowColor: '#FFFFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 2,
  },
  particlesContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  particle: {
    position: 'absolute',
    width: 2,
    height: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 1,
  },
  bgGradient1: {
    position: 'absolute',
    width: width * 1.5,
    height: 400,
    borderRadius: 300,
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    top: -100,
    left: -200,
  },
  bgGradient2: {
    position: 'absolute',
    width: width * 1.2,
    height: 350,
    borderRadius: 280,
    backgroundColor: 'rgba(168, 85, 247, 0.06)',
    top: 200,
    right: -150,
  },
  bgGradient3: {
    position: 'absolute',
    width: width * 1.3,
    height: 380,
    borderRadius: 320,
    backgroundColor: 'rgba(34, 197, 94, 0.05)',
    bottom: -100,
    left: -100,
  },
  bgGradient4: {
    position: 'absolute',
    width: width * 1.4,
    height: 360,
    borderRadius: 310,
    backgroundColor: 'rgba(249, 115, 22, 0.04)',
    top: '50%',
    right: -200,
  },
  pathContainer: {
    width: width,
    position: 'relative',
    zIndex: 1,
  },
  levelContainer: {
    position: 'absolute',
    alignItems: 'center',
    width: 80,
  },
  levelButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  completedLevel: {
    backgroundColor: '#2A2D3A',
    borderWidth: 2,
    borderColor: '#3B82F6',
  },
  activeLevel: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#3B82F6',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 15,
  },
  lockedLevel: {
    backgroundColor: '#2A2D3A',
    opacity: 0.4,
  },
  levelLabel: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: 'bold',
    color: '#6B7280',
    maxWidth: 80,
    textAlign: 'center',
  },
  activeLevelLabel: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#3B82F6',
    maxWidth: 80,
    textAlign: 'center',
  },
  lockedLabel: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: 'bold',
    color: '#4B5563',
    maxWidth: 80,
    textAlign: 'center',
  },
  badge: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    marginTop: 4,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#3B82F6',
  },
  mascotContainer: {
    position: 'absolute',
    top: -64,
    zIndex: 10,
  },
  mascot: {
    fontSize: 48,
  },
  // ===== Modal Styles =====
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#1F2128',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '85%',
    minHeight: '50%',
    paddingBottom: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  modalBody: {
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  modalFooter: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  closeModalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#3B82F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  // Info Container Styles
  infoContainer: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  iconBox: {
    width: 80,
    height: 80,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  largeIcon: {
    fontSize: 48,
  },
  infoTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  infoText: {
    fontSize: 14,
    color: '#E5E7EB',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 20,
    paddingHorizontal: 12,
  },
  benefitsBox: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    borderLeftWidth: 4,
    borderLeftColor: '#3b82f6',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 16,
    width: '100%',
  },
  benefitsTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  benefitItem: {
    fontSize: 14,
    color: '#E5E7EB',
    marginVertical: 6,
  },
  tipBox: {
    flexDirection: 'row',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 20,
    alignItems: 'flex-start',
    gap: 10,
  },
  tipText: {
    fontSize: 13,
    color: '#E5E7EB',
    flex: 1,
    lineHeight: 20,
  },
  streakInfo: {
    backgroundColor: 'rgba(249, 115, 22, 0.1)',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(249, 115, 22, 0.3)',
    alignItems: 'center',
    width: '100%',
  },
  streakLabel: {
    fontSize: 14,
    color: '#9CA3AF',
    marginBottom: 8,
  },
  streakCount: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#f97316',
  },
  streakSubText: {
    fontSize: 13,
    color: '#E5E7EB',
    marginTop: 6,
  },
  // Badge Shop Styles
  diamondDisplayBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    marginBottom: 20,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  diamondDisplayText: {
    fontSize: 16,
    color: '#E5E7EB',
    fontWeight: '500',
  },
  diamondCount: {
    fontSize: 16,
    color: '#3B82F6',
    fontWeight: '700',
  },
  badgesShopGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: 'space-between',
    marginVertical: 16,
    marginBottom: 20,
  },
  badgeShopCard: {
    width: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  badgeShopIconContainer: {
    width: 56,
    height: 56,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    position: 'relative',
  },
  badgeOwnedContainer: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    borderWidth: 2,
    borderColor: '#22c55e',
  },
  badgeShopIcon: {
    fontSize: 28,
  },
  ownedBadge: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    width: 24,
    height: 24,
    backgroundColor: '#22c55e',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#1F2128',
  },
  badgeShopName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 4,
  },
  badgeShopDesc: {
    fontSize: 11,
    color: '#9CA3AF',
    marginBottom: 8,
    textAlign: 'center',
  },
  buyButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#3B82F6',
    alignItems: 'center',
    width: '100%',
  },
  buyButtonDisabled: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    opacity: 0.6,
  },
  buyButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  ownedButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    alignItems: 'center',
    width: '100%',
    borderWidth: 1,
    borderColor: '#22c55e',
  },
  ownedButtonText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#22c55e',
  },
});

export default styles;
